# Generated by Django 5.1.7 on 2025-03-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PublicationModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("type_of_publication", models.CharField(choices=[("a", "Article"), ("c", "Conference")])),
                ("publisher", models.CharField(max_length=255)),
                ("language", models.CharField(default="en", max_length=2)),
                ("publication_date", models.DateField()),
            ],
            options={
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
                "ordering": ("-publication_date",),
            },
        ),
    ]
