# Generated by Django 5.1.7 on 2025-03-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EducationModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("start_year", models.PositiveBigIntegerField()),
                ("end_year", models.PositiveBigIntegerField()),
                ("place", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=60)),
                ("country", models.CharField(max_length=60)),
            ],
            options={
                "ordering": ["-start_year", "-end_year"],
            },
        ),
    ]
