# Generated by Django 5.1.7 on 2025-03-27 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationPlaceModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country_name", models.CharField(max_length=60)),
                ("city", models.CharField(max_length=60)),
                ("place_name", models.CharField(max_length=60)),
            ],
            options={
                "verbose_name": "Education Place",
                "verbose_name_plural": "Education Places",
                "ordering": ("country_name", "city", "place_name"),
            },
        ),
        migrations.AlterModelOptions(
            name="educationmodel",
            options={
                "ordering": ["-start_year", "-end_year"],
                "verbose_name": "Education",
                "verbose_name_plural": "Educations",
            },
        ),
        migrations.RemoveField(
            model_name="educationmodel",
            name="city",
        ),
        migrations.RemoveField(
            model_name="educationmodel",
            name="country",
        ),
        migrations.AlterField(
            model_name="educationmodel",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="educations",
                to="education.educationplacemodel",
            ),
        ),
    ]
